# Generated by Django 2.0.1 on 2018-01-27 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='floorplans')),
                ('width_offset', models.FloatField(default=1.0)),
                ('height_offset', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loc_type', models.CharField(choices=[('DESK', 'Desk'), ('OFFICE', 'Office'), ('CONFR', 'Conference Room'), ('COMMON', 'Common Area'), ('RESTROOM', 'Restroom'), ('PUBLIC', 'Public Area'), ('PRIVATE', 'Private Area'), ('MISC', 'Miscellaneous')], max_length=50)),
                ('details', models.CharField(blank=True, max_length=250)),
                ('ext', models.IntegerField(blank=True, null=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='floorplans.FloorPlan')),
            ],
        ),
    ]
