# Generated by Django 2.0.1 on 2018-02-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorplans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='height_offset',
            new_name='height_ratio',
        ),
        migrations.RenameField(
            model_name='floorplan',
            old_name='width_offset',
            new_name='width_ratio',
        ),
    ]
