# Generated by Django 2.0.1 on 2018-02-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorplans', '0002_auto_20180204_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='ext',
            new_name='extension',
        ),
    ]
