# Generated by Django 2.0.1 on 2018-02-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorplans', '0003_auto_20180204_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='width_ratio',
            new_name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='height_ratio',
        ),
    ]
