# Generated by Django 2.0.1 on 2018-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplans', '0004_auto_20180208_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
