# Generated by Django 2.0.1 on 2018-02-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplans', '0005_auto_20180211_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
