# Generated by Django 2.0.1 on 2018-02-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorplans', '0006_floorplan_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='user',
            new_name='owner',
        ),
    ]
