# Generated by Django 2.0.1 on 2018-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplans', '0007_auto_20180213_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='aspect_ratio',
            new_name='height',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(height_field=models.FloatField(default=1.0), upload_to='floorplans', width_field=models.FloatField(default=1.0)),
        ),
    ]
